import type { NextPage } from 'next';
import Head from 'next/head';
import { ChangeEvent, useState } from 'react';
import { gto9 } from 'g-to-9';

const Home: NextPage = () => {
  const [text, setText] = useState('');

  const onChangeHandler = (e: ChangeEvent<HTMLInputElement>) => {
    setText(e.target.value);
  };
  return (
    <>
      <Head>
        <title>gto9</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main">
        <input
          type="text"
          className="input"
          value={text}
          onChange={onChangeHandler}
        />
        <div className="output">{gto9(text)}</div>
      </div>
    </>
  );
};

export default Home;
